apiVersion: v1
kind: Service
metadata:
  name: rust-app-svc
spec:
  type: NodePort
  selector:
    app: rust-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31200