apiVersion: v1
kind: Service
metadata:
  name: mock-pagamentos-svc
spec:
  type: NodePort
  selector:
    app: mock-pagamentos-pod
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 31300

---

apiVersion: v1
kind: Service
metadata:
  name: mock-pagamentos-lb-svc
spec:
  type: LoadBalancer
  selector:
    app: mock-pagamentos-pod
  ports:
    - port: 9000
      targetPort: 9000
