FROM messense/rust-musl-cross:x86_64-musl as builder

ENV DB_URL=postgres://postgres:postgres@localhost:5432
ENV SECRET=secret_from_docker
ENV ENV=dev
ENV RUST_BACKTRACE=1

RUN rustup update nightly && \
    rustup target add --toolchain nightly x86_64-unknown-linux-musl

RUN rustup default nightly

RUN cargo install cargo-watch

WORKDIR /app


COPY . /app

VOLUME ["/app"]

# RUN cargo watch -x "run api --path ./src"
RUN cargo run api